### ISSUE TITLE
Weird underline when using flavours that are not mocha

### ISSUE THREAD

**Issue by rubyowo** [catppuccin/zsh-syntax-highlighting#7]
![image](https://user-images.githubusercontent.com/105302757/206842403-cd7d95b5-142e-4dc8-9bdf-1385cd36d5a1.png)
this appears to only be happening with directories and files

**Comment by hyperreal64** [comment]
Hello. When you say weird underline, do you mean the underlining itself is the problem, or do you mean how it uses the same color as the path separator?

If you don't like the underlining itself, you can disable it by editing lines 60-63 of the catppuccin_macchiato-zsh-syntax-highlighting.zsh file and removing the "underline" portion. So those lines should now look like this:

```shell
ZSH_HIGHLIGHT_STYLES[path]='fg=#cad3f5'
ZSH_HIGHLIGHT_STYLES[path_pathseparator]='fg=#ed8796'
ZSH_HIGHLIGHT_STYLES[path_prefix]='fg=#cad3f5'
ZSH_HIGHLIGHT_STYLES[path_prefix_pathseparator]='fg=#ed8796'
```

If you don't like how the underline color matches the color of the path separator, but you still want to keep the underline, the best way is to edit lines 60-63 of the syntax highlighting file to look like this:

```shell
ZSH_HIGHLIGHT_STYLES[path]='fg=#cad3f5,underline'
ZSH_HIGHLIGHT_STYLES[path_pathseparator]='fg=#ed8796'
ZSH_HIGHLIGHT_STYLES[path_prefix]='fg=#cad3f5,underline'
ZSH_HIGHLIGHT_STYLES[path_prefix_pathseparator]='fg=#ed8796'
```

This will result in having gaps in the underlining for the path separator. In my opinion, this looks better anyway, so I might make this change in the repo for all flavors. I will also provide a no-path-underline file for each flavor, so that users can decide themselves instead of having to edit the file.

Let me know if this helps!

**Comment by rubyowo** [comment]
thanks!
